# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WF_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Role', models.CharField(blank=True, max_length=100, null=True)),
                ('DateOfReceipt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
