# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno', '0002_auto_20170427_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wfaccount',
            old_name='DateOfReceipt',
            new_name='Date_Of_Receipt',
        ),
    ]
