# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno', '0005_auto_20170502_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='RankImage',
            field=models.FileField(blank=True, upload_to='Inferno/static/images/Ranks'),
        ),
    ]
