# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno', '0007_auto_20170505_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='RankOwner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
