# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno', '0008_rank_rankowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RankImageUpload', models.FileField(blank=True, upload_to='Inferno/static/images/Ranks')),
            ],
        ),
        migrations.RemoveField(
            model_name='rank',
            name='RankImageUpload',
        ),
    ]
