# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno', '0009_auto_20170505_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.AddField(
            model_name='wfaccount',
            name='RankImage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
