# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno', '0010_auto_20170505_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfaccount',
            name='RankImage',
        ),
    ]
