# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno', '0011_remove_wfaccount_rankimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfaccount',
            name='RankImage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
